# Generated by Django 4.2.6 on 2023-10-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('body_type', models.CharField(max_length=20)),
                ('engine_volume', models.IntegerField()),
            ],
        ),
    ]
